name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

env:
  REGISTRY: docker.io
  API_IMAGE_NAME: jeiferson/rinha-backend-2025
  LB_IMAGE_NAME: jeiferson/rinha-backend-2025-lb

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platform: 
          - { name: "amd64", dockerfile: "Dockerfile" }
          - { name: "arm64", dockerfile: "Dockerfile_arm64" }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for API
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
        tags: |
          type=ref,event=branch,suffix=-${{ matrix.platform.name }}
          type=ref,event=pr,suffix=-${{ matrix.platform.name }}
          type=semver,pattern={{version}},suffix=-${{ matrix.platform.name }}
          type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.platform.name }}
          type=semver,pattern={{major}},suffix=-${{ matrix.platform.name }}
          type=raw,value=latest-${{ matrix.platform.name }},enable={{is_default_branch}}

    - name: Build and push API Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.platform.dockerfile }}
        platforms: linux/${{ matrix.platform.name }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=api-${{ matrix.platform.name }}
        cache-to: type=gha,mode=max,scope=api-${{ matrix.platform.name }}

  build-and-push-lb:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for Load Balancer
      id: meta-lb
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.LB_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Load Balancer Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./load-balancer
        file: ./load-balancer/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-lb.outputs.tags }}
        labels: ${{ steps.meta-lb.outputs.labels }}
        cache-from: type=gha,scope=lb
        cache-to: type=gha,mode=max,scope=lb